export enum Collection {
    Inquiries = 'inquiries',
    AdminUsers = 'adminUsers',
    Contacts = 'contacts',
    TempAssignClaim = 'tempAssignClaim',
    Loans = 'loans',
    Borrowers = 'borrowers',
    Persions = 'persions',
    GpsIntegrations = 'gpsIntegrations',
    AmortizationSchedule = 'amortizationSchedule',
    Installments = 'installments',
    LoanPayments = 'loanPayments',
    PaymentLedger = 'paymentLedger',
    PaymentTransactions = 'paymentTransactions',
}
